### PR TITLE
Faster and less resourceful DB check implementation, fix #451

### LINKED ISSUE #451: 2.5.3 Running out of heap memory when doing the new database check
Updated my pi3 to 2.5.3 and get the following error

```
Oct 06 17:49:17 BURSTNODE java[27198]: [INFO] 2020-10-06 17:49:17 brs.BlockchainProcessorImpl - Checking database state (it can take a minute or two)...
Oct 06 17:50:51 BURSTNODE java[27198]: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

I flashed ubuntu 64 bit on it to try and 64bit java but still the same issue.

### PR DESCRIPTION
**Pull request by jjos2372**

### CODE REVIEW

**Review by ohager — APPROVED** [review]
lgtm... although I'm not capable t go through the "business" logic itself

File: src/brs/BlockchainProcessorImpl.java [hunk 1]
```diff
@@ -771,31 +765,46 @@ private void addBlock(Block block) {
...
+      }
+    }
+    for (Transaction transaction : blockchain.getTransactions(nullAccount, (byte)0, (byte)2, 0, true)) {
+      Attachment attachment = transaction.getAttachment();
+      if(attachment instanceof PaymentMultiSameOutCreation) {
+        PaymentMultiSameOutCreation multiOut = (PaymentMultiSameOutCreation) attachment;
+        for (Long recipient : multiOut.getRecipients()) {
+          if(recipient == nullAccount.getId())
+            totalBurnt += transaction.getAmountNQT()/multiOut.getRecipients().size();
+        }
```
Comment (blankey1337) [inline src/brs/BlockchainProcessorImpl.java:797]: damn fine detective work

**Review by blankey1337 — APPROVED** [review]
